"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { Plan } from "@/lib/types";
import {
  LANGUAGES,
  briefingFacts,
  renderBriefing,
  type Language,
} from "@/lib/briefing";
import { Panel, Pill, Segmented } from "./ui";

type Source = "template" | "nugen";

/**
 * Supervisor briefing.
 *
 * Two things this panel is built to demonstrate, beyond producing text:
 *
 * 1. Voice. The briefing is spoken aloud through the Web Speech API — no
 *    telephony dependency to fail on a conference network. Exotel/IVR is the
 *    production path and is labelled as such rather than claimed.
 * 2. That the model is outside the safety decision path. The source toggle
 *    switches between the deterministic renderer and the Nugen aligned model,
 *    and the schedule above does not move. That is the point.
 */
export function BriefingPanel({ plan }: { plan: Plan }) {
  const [lang, setLang] = useState<Language>("mr");
  const [source, setSource] = useState<Source>("template");
  const [nugenText, setNugenText] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [nugenError, setNugenError] = useState<string | null>(null);
  const [speaking, setSpeaking] = useState(false);
  const [acknowledged, setAcknowledged] = useState(false);

  const facts = useMemo(() => briefingFacts(plan), [plan]);
  const fallbackText = useMemo(() => renderBriefing(facts, lang), [facts, lang]);
  const text = source === "nugen" && nugenText ? nugenText : fallbackText;

  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

  // A new plan or language invalidates any model output we were showing.
  useEffect(() => {
    setNugenText(null);
    setNugenError(null);
    setAcknowledged(false);
  }, [plan.site.id, plan.date, plan.blocks.length, lang]);

  useEffect(() => {
    return () => {
      if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    };
  }, []);

  const generate = async () => {
    setLoading(true);
    setNugenError(null);
    try {
      const res = await fetch("/api/brief", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ facts, lang }),
      });
      const json = (await res.json()) as {
        text?: string;
        source?: Source;
        error?: string;
      };
      if (json.text && json.source === "nugen") {
        setNugenText(json.text);
        setSource("nugen");
      } else {
        setNugenError(json.error ?? "Nugen unavailable — showing the deterministic briefing.");
        setSource("template");
      }
    } catch {
      setNugenError("Could not reach the briefing service.");
      setSource("template");
    } finally {
      setLoading(false);
    }
  };

  const speak = () => {
    if (typeof window === "undefined" || !window.speechSynthesis) return;
    const synth = window.speechSynthesis;
    if (speaking) {
      synth.cancel();
      setSpeaking(false);
      return;
    }
    synth.cancel();
    const u = new SpeechSynthesisUtterance(text);
    u.lang = LANGUAGES.find((l) => l.code === lang)?.bcp47 ?? "en-IN";
    u.rate = 0.92;
    u.onend = () => setSpeaking(false);
    u.onerror = () => setSpeaking(false);
    utteranceRef.current = u;
    setSpeaking(true);
    synth.speak(u);
  };

  return (
    <Panel
      title="Supervisor briefing"
      aside={
        <span className="tnum text-[11px] text-[var(--color-ink-muted)]">
          to {plan.site.supervisor}
        </span>
      }
    >
      <div className="flex flex-wrap items-center gap-x-5 gap-y-3 border-b border-[var(--color-rule)] px-3.5 py-3">
        <Segmented
          label="Language"
          value={lang}
          onChange={setLang}
          options={LANGUAGES.map((l) => ({
            value: l.code,
            label: l.native,
            title: l.label,
          }))}
        />
        <Segmented
          label="Source"
          value={source}
          onChange={(s) => {
            if (s === "nugen" && !nugenText) {
              void generate();
            } else {
              setSource(s);
            }
          }}
          disabled={loading}
          options={[
            { value: "template" as Source, label: "Deterministic", title: "Rendered directly from the engine output" },
            { value: "nugen" as Source, label: "Nugen aligned", title: "Generated by the Nugen aligned model" },
          ]}
        />
        {loading && (
          <span className="tnum text-[11px] text-[var(--color-ink-faint)]">
            generating…
          </span>
        )}
      </div>

      <div className="px-3.5 py-3.5">
        <blockquote
          lang={LANGUAGES.find((l) => l.code === lang)?.bcp47}
          className="m-0 whitespace-pre-line border-l-2 border-[var(--color-ink)] bg-[var(--color-paper-sunk)] px-4 py-3.5 text-[13.5px] leading-[1.75]"
        >
          {text}
        </blockquote>

        {nugenError && (
          <p className="mt-2.5 text-[11px] text-[var(--color-accent)]">{nugenError}</p>
        )}

        <div className="mt-3.5 flex flex-wrap items-center gap-2.5">
          <button
            type="button"
            onClick={speak}
            className="inline-flex items-center gap-2 rounded-[2px] border border-[var(--color-ink)] bg-[var(--color-ink)] px-3 py-1.5 font-mono text-[11px] uppercase tracking-[0.1em] text-[var(--color-paper)] transition-opacity hover:opacity-85"
          >
            {speaking ? "■ stop" : "▶ play briefing"}
          </button>

          <button
            type="button"
            onClick={() => setAcknowledged((a) => !a)}
            className={`inline-flex items-center gap-2 rounded-[2px] border px-3 py-1.5 font-mono text-[11px] uppercase tracking-[0.1em] transition-colors ${
              acknowledged
                ? "border-[var(--color-safe)] text-[var(--color-safe)]"
                : "border-[var(--color-rule-strong)] text-[var(--color-ink-muted)] hover:bg-[var(--color-paper-sunk)]"
            }`}
          >
            {acknowledged ? "✓ acknowledged" : "mark acknowledged"}
          </button>

          <Pill>SMS / IVR via Exotel in production</Pill>
        </div>

        <p className="mt-3 border-t border-[var(--color-rule)] pt-2.5 text-[10.5px] leading-relaxed text-[var(--color-ink-muted)]">
          The aligned model phrases the briefing; it does not compute it. Every time,
          threshold and volume above comes from the ISO 7933 and optimiser output — switch
          the source and the schedule does not move. A model failure cannot produce an
          unsafe shift.
        </p>
      </div>
    </Panel>
  );
}
